export const ADD_GROCERY = "ADD_GROCERY";
export const LOAD_GROCERIES = "LOAD_GROCERIES";
export const REMOVE_GROCERY = "REMOVE_GROCERY";
export const GROCCERY_ERROR = "GROCCERY_ERROR";
export const BUY_OR_DROP_GROCERY = "BUY_OR_DROP_GROCERY";